### ISSUE TITLE
All random feedback from Brian

### ISSUE THREAD

**Issue by bdeitte** [DailyFeats/eno-migration#3]
I'll just put it all together.  

1. Make sure all new changes, even for this feedback, goes into PRs.
2. As mentioned in chat, the README needs more basic information on what the repository is for and what it does.
3. Remove "tests" from package.json :)
4. Can you add "ebn" to the shouldSkipFeed() list?  This came in as a request from the EDI team to add there.

Changes look good to me otherwise, nice to see the code split up.

**Comment by t2n** [comment]
feedback implemented
